# Step 0: Analytic data

```{r, cache=TRUE, echo=FALSE}
load("data/analytic13recoded.RData")
load("data/analytic15recoded.RData")
load("data/analytic17recoded.RData")
```

## Merge 2013-18 datasets


Data from 3 cycles are merged based on available covariates. 

```{r, cache=TRUE, echo=FALSE}
data.merged0 <- rbind(analytic13, analytic15, analytic17)
# dim(data.merged0)
data.merged <- droplevels(data.merged0)
data.complete <- na.omit(data.merged)
#save(data.complete, file = "data/analytic3cycles.RData")
```

::: column-margin
Only complete cases retained, and survey features/weights were ignored for simplicity.
::: 

## Summary statistics



```{r, cache=TRUE, echo=FALSE}
tab1 <- table1::table1(x = ~ age.cat + sex + education + race + 
                         marital + income + born + year + 
                         diabetes.family.history + smoking + diet.healthy + 
                         physical.activity + medical.access + sleep + 
                         systolicBP + diastolicBP + uric.acid + 
                         protein.total + bilirubin.total + phosphorus + 
                         sodium + potassium + globulin + calcium.total + 
                         high.cholesterol| obese, data = data.complete)
tab1
```

::: column-margin
Investigator specified covariates stratified by the exposure (obesity)
::: 