# Take-aways

## What are the strengths

1.  Comprehensive comparison of various algorithms, going beyond the current literature.

2.  Plasmode simulation includes realistic considerations:

  -   Complex function
  -   Many noise variables available
  -   Based on an open dataset

3.  Comprehensive list of performance measures considered:

  -   Coverage
  -   relative error in model SE

## What could improve

1.  More proxies!

  -   Others have used $k = 10$ in the same context to compare

2.  Investigate additional double cross-fit versions:

  -   Only kitchen sink used

## Conclusions

::: callout-tip
# High-dimensional <mark>proxy adjustment</mark> context

1.  Employ TMLE whenever possible for more unbiased and accurate results.

-   TMLE methods have competitive advantage while adjusting for too many proxies (**high-dimensional**; beyond low dimensions where it is now popular).

2.  Exercise caution with Super Learner, considering the trade-offs between smooth and non-smooth learners.
:::
